export const enMessages = {
  'Shared.loading': 'Loading',
  'Shared.error': 'An error occured',
  'Shared.submit': 'Submit',
  'Shared.tags': 'Tags',
  'Shared.logIn': 'Log in',
  'Shared.verdict': 'Verdict',
  'Shared.noneYet': 'None yet',
  'Shared.books': 'Books',
  'Shared.movies': 'Movies',
  'Shared.games': 'Games',
  'Shared.search': 'Search',

  'Login.usernameValidationError': 'Username must be 3-30 symbols long',
  'Login.passwordValidationError': 'Password must be 3-30 symbols long',
  'Login.createNewAccount': 'Create new account',

  'Main.newReviews': 'New reviews',
  'Main.highestRated': 'Highest rated',
  'Main.noReviews': 'No reviews yet',
  'Main.cancelFilter': 'Cancel filter',

  'ReviewCard.readReview': 'Read review',

  'Review.reviewOf': 'Review of',
  'Review.yourRate': 'Your rate',
  'Review.avgRate': 'Average rate',

  'MyReviews.title': 'Title',
  'MyReviews.product': 'Product',
  'MyReviews.group': 'Group',
  'MyReviews.avgRating': 'Avg. rating',
  'MyReviews.actions': 'Actions',
  'MyReviews.addNewReview': 'Add new review',
  'MyReviews.yourReviews': 'Your reviews',
  'MyReviews.usernameReviews': '{username} reviews',

  'ReviewEditor.createNewReview': 'Create new review',
  'ReviewEditor.editReview': 'Edit review',
  'ReviewEditor.defaultReviewText': '**Write your review here** (*Markdown syntax supported*)',
  'ReviewEditor.seePreview': 'See preview',
  'ReviewEditor.pic': 'Pic',
  'ReviewEditor.tagsPlaceholder': 'Press Enter to add a new tag',
  'ReviewEditor.textInputs.title': 'Title',
  'ReviewEditor.textInputs.titlePlaceholder': 'Enter title',
  'ReviewEditor.textInputs.product': 'Product',
  'ReviewEditor.textInputs.productPlaceholder': 'Enter product',
  'ReviewEditor.text': 'Text',
  'ReviewEditor.selectInputs.group': 'Group',
  'ReviewEditor.selectInputs.groupPlaceholder': 'Select group',
  'ReviewEditor.selectInputs.groupValidationError': 'Please select group',
  'ReviewEditor.selectInputs.verdict': 'Verdict',
  'ReviewEditor.selectInputs.verdictPlaceholder': 'Select verdict',
  'ReviewEditor.selectInputs.verdictValidationError': 'Please select verdict',
  'ReviewEditor.textValidationError': 'The text must be 10-2000 symbols long',

  'Userlist.name': 'Name',
  'Userlist.role': 'Role',
  'Userlist.likes': 'Likes',
  'Userlist.adminAccessTitle': 'Admin access to users',

  'Comments.header': 'Comments',
  'Comments.addComment': 'Add comment',
  'Comments.validationError': 'Comments must be 3-100 symbols long',
  'Comments.placeholder': 'Type comment here',

  'NavbarButtons.userlist': 'Userlist',
  'NavbarButtons.logOut': 'Log out',

  'PicUpload.putImageHere': `Drag 'n' drop an image file here`,
  'PicUpload.removePic': 'Remove pic',
}
